spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      minimum-idle: 3
      idle-timeout: 0
      maximum-pool-size: 15
      pool-name: local-pool-${spring.application.name}
      max-lifetime: 1800000
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  api-docs:
    enabled: true
server:
  http2:
    enabled: true
  port: ${SERVER_PORT}
  servlet:
    context-path: /${spring.application.name}
jwt:
  secret: ${JWT_SECRET}
recaptcha:
  secret: ${RECAPTCHA_SECRET}
cors:
  allowed:
    origins: ${CORS_ALLOWED_ORIGINS}
app:
  cookie:
    secure: false
